version: 2.1

orbs:
  node: circleci/node@4.5.1
jobs:
  test:
   executor: node/default
   steps:
    - checkout
    - node/install-packages
    - run: | 
        npm run test
      
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: |
          npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./build
            - ./kubernetes/kustomize/overlays
  publish:
    docker:
      - image: cimg/node:12.0.0
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          cp -R /tmp/workspace/build ./build
          TAG=0.$CIRCLE_BUILD_NUM
          docker build -t codekagei/quizzler:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push codekagei/quizzler:$TAG

  generateYAML:
    docker:
      - image: cimg/base:2020.06
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          TAG=0.$CIRCLE_PREVIOUS_BUILD_NUM
          git clone https://github.com/themmyloluwaa/quizzler-deployment.git /tmp/quizzler-deployment
          cd /tmp/quizzler-deployment/kubernetes/kustomize/base
          sed -i 's/\(codekagei\/quizzler\)\(.*\)/\1:'$TAG'/' ./quizzler-deployment.yaml
          cd ../../../
          git config credential.helper 'cache --timeout=120'
          git config user.email "codekagei@gmail.com"
          git config user.name "Temiloluwa Philip Ojo"
          git add .
          git commit -m 'edited kustomization file with new image  tag $TAG for staging environment'
          git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/themmyloluwaa/quizzler-deployment.git main


          



    

workflows:
  version: 2
  Test-Build-Publish-Deploy:
    jobs:
      - test
      - build:
         requires:
           - test
      - publish:
          requires:
           - build
          filters:
            branches:
              only:
                - main
      - generateYAML:
          requires:
           - publish
          filters:
            branches:
              only:
                - main
            
        